Naive Bayes 

In [6]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.preprocessing import OneHotEncoder
import zipfile
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

encoder = OneHotEncoder()

# train dataset
df_train = pd.read_csv('train_dataset.csv')
categorical_cols = ['language', 'country', 'content_rating', 'movie_title', 'actor_3_name']
encoded_df = pd.DataFrame(encoder.fit_transform(df_train[categorical_cols]).toarray(), columns=encoder.get_feature_names_out(categorical_cols))

# Concatenate the encoded columns with the original DataFrame
df_encoded = pd.concat([df_train, encoded_df], axis=1)

# Drop the original categorical columns
df_encoded.drop(categorical_cols, axis=1, inplace=True)
drop = ['actor_1_name', 'actor_2_name', 'genres', 'plot_keywords', 'title_embedding', 'director_name']
df_encoded.drop(drop, axis=1, inplace=True)

X_train_1 = df_encoded.iloc[:, :-1]
y_train_1 = df_encoded['imdb_score_binned']

# test dataset 
df_test = pd.read_csv('test_dataset.csv')
encoded_df_test = pd.DataFrame(encoder.fit_transform(df_test[categorical_cols]).toarray(), columns=encoder.get_feature_names_out(categorical_cols))

# Concatenate the encoded columns with the original DataFrame
df_encoded_test= pd.concat([df_test, encoded_df_test], axis=1)

# Drop the original categorical columns
df_encoded_test.drop(categorical_cols, axis=1, inplace=True)
df_encoded_test.drop(drop, axis=1, inplace=True)
X_test = df_encoded_test.iloc[:, :-1]

# X_train, X_test, y_train, y_test_1 = train_test_split(df_encoded.iloc[:,:-1], df_encoded.iloc[:,-1], test_size=0.2, random_state=42)
print(X_test)


      id  num_critic_for_reviews  duration  director_facebook_likes  \
0      1                      27       118                       14   
1      2                     339       141                        0   
2      3                      78        95                       89   
3      4                     226       117                        0   
4      5                      97       104                       38   
..   ...                     ...       ...                      ...   
747  748                     179        93                        0   
748  749                     393       105                      335   
749  750                      55       117                      133   
750  751                      85        72                        0   
751  752                      35        87                        4   

     actor_3_facebook_likes  actor_1_facebook_likes      gross  \
0                       400                    2000    2246000   
1              

In [7]:
zip_train_actor_1_name = 'features_countvec/train_countvec_features_actor_1_name.npy'
zip_train_actor_2_name = 'features_countvec/train_countvec_features_actor_2_name.npy'
zip_train_director_name = 'features_countvec/train_countvec_features_director_name.npy'
zip_train_genres = 'features_doc2vec/train_doc2vec_features_genre.npy'
zip_train_plot_keywords = 'features_doc2vec/train_doc2vec_features_plot_keywords.npy'
zip_train_title_embedding = 'features_fasttext/train_fasttext_title_embeddings.npy'

data_director = np.load(zip_train_director_name)
data_frame_director = pd.DataFrame(data_director)
data_frame_pre_director = data_frame_director.add_prefix('director_name_')
X_train_1 = pd.concat([X_train_1, data_frame_pre_director], axis=1)
# X_train = pd.concat([X_train, data_frame_pre_director], axis=1)

data_actor2 = np.load(zip_train_actor_2_name)
data_frame_actor2 = pd.DataFrame(data_actor2)
data_frame_pre_actor2 = data_frame_actor2.add_prefix('actor_2_name_')
X_train_1 = pd.concat([X_train_1, data_frame_pre_actor2], axis=1)
# X_train = pd.concat([X_train, data_frame_pre_actor2], axis=1)

data_actor1 = np.load(zip_train_actor_1_name)
data_frame_actor1 = pd.DataFrame(data_actor1)
data_frame_pre_actor1 = data_frame_actor1.add_prefix('actor_1_name_')
X_train_1 = pd.concat([X_train_1, data_frame_pre_actor1], axis=1)
# X_train = pd.concat([X_train, data_frame_pre_actor1], axis=1)

genre = np.load(zip_train_genres)
data_frame_genre = pd.DataFrame(genre)
data_frame_pre_genres = data_frame_genre.add_prefix('genres_')
X_train_1 = pd.concat([X_train_1, data_frame_pre_genres], axis=1)
# X_train = pd.concat([X_train, data_frame_pre_genres], axis=1)

plot_keywords = np.load(zip_train_plot_keywords)
data_plot_keywords = pd.DataFrame(plot_keywords)
data_frame_plot_key = data_plot_keywords.add_prefix('plot_keywords_')
X_train_1 = pd.concat([X_train_1, data_frame_plot_key], axis=1)
# X_train = pd.concat([X_train, data_frame_plot_key], axis=1)

title_embedding = np.load(zip_train_title_embedding)
data_title_embedding = pd.DataFrame(title_embedding)
data_frame_pre_title_embedding = data_title_embedding.add_prefix('title_embedding_')
X_train_1 = pd.concat([X_train_1, data_frame_pre_title_embedding], axis=1)
# X_train = pd.concat([X_train, data_frame_plot_key], axis=1)

# X_train, X_test, y_train, y_test_1 = train_test_split(X_train_1, y_train_1, test_size=0.2, random_state=42)

pd.set_option('display.max_rows', None)
# X_train_1.columns
np.shape(X_train_1)
# X_train_1
# print(X_train)  



(3004, 12637)

In [8]:
zip_train_actor_1_name = 'features_countvec/train_countvec_features_actor_1_name.npy'
zip_train_actor_2_name = 'features_countvec/train_countvec_features_actor_2_name.npy'
zip_train_director_name = 'features_countvec/train_countvec_features_director_name.npy'
zip_train_genres = 'features_doc2vec/train_doc2vec_features_genre.npy'
zip_train_plot_keywords = 'features_doc2vec/train_doc2vec_features_plot_keywords.npy'

data_director = np.load(zip_train_director_name)

print(data_director)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
print(np.shape(X_test))

zip_test_actor_1_name = 'features_countvec/test_countvec_features_actor_1_name.npy'
zip_test_actor_2_name = 'features_countvec/test_countvec_features_actor_2_name.npy'
zip_test_director_name = 'features_countvec/test_countvec_features_director_name.npy'
zip_test_genre = 'features_doc2vec/test_doc2vec_features_genre.npy'
zip_test_plot_keywords = 'features_doc2vec/test_doc2vec_features_plot_keywords.npy'
zip_test_title_embedding = 'features_fasttext/test_fasttext_title_embeddings.npy'

data_director = np.load(zip_test_director_name)
data_frame_director = pd.DataFrame(data_director)
data_frame_pre_director = data_frame_director.add_prefix('director_name_')
X_test = pd.concat([X_test, data_frame_pre_director], axis=1)
print(np.shape(X_test))

data_actor2 = np.load(zip_test_actor_2_name)
data_frame_actor2 = pd.DataFrame(data_actor2)
data_frame_pre_actor2 = data_frame_actor2.add_prefix('actor_2_name_')
X_test = pd.concat([X_test, data_frame_pre_actor2], axis=1)
print(np.shape(X_test))

data_actor1 = np.load(zip_test_actor_1_name)
data_frame_actor1 = pd.DataFrame(data_actor1)
data_frame_pre_actor1 = data_frame_actor1.add_prefix('actor_1_name_')
X_test = pd.concat([X_test, data_frame_pre_actor1], axis=1)
print(np.shape(X_test))

genre = np.load(zip_test_genre)
data_genre = pd.DataFrame(genre)
data_frame_genre = data_genre.add_prefix('genres_')
X_test = pd.concat([X_test, data_frame_genre], axis=1)
print(np.shape(X_test))

plot_keywords = np.load(zip_test_plot_keywords)
data_plot_keywords = pd.DataFrame(plot_keywords)
data_frame_plot_keywords = data_plot_keywords.add_prefix('plot_keywords_')
X_test = pd.concat([X_test, data_frame_plot_keywords], axis=1)
print(np.shape(X_test))

title_embedding = np.load(zip_test_title_embedding)
data_title_embedding = pd.DataFrame(title_embedding)
data_frame_title_embedding = data_title_embedding.add_prefix('title_embedding_')
X_test = pd.concat([X_test, data_frame_title_embedding], axis=1)


pd.set_option('display.max_rows', None)
# print(np.shape(data_frame_director))
# print(np.shape(data_frame_actor2))
# print(np.shape(data_frame_actor1))
# print(np.shape(data_frame_genre))
# print(np.shape(data_frame_plot_keywords))
np.shape(X_test)




(752, 1486)
(752, 3599)
(752, 6518)
(752, 8581)
(752, 8681)
(752, 8781)


(752, 8881)

In [30]:
# # print(y_train_1)
# np.shape(y_train_1)
# zip_y_train_titleembed = 'features_fasttext/train_fasttext_title_embeddings.npy'

# # title_embedding = np.load(zip_y_train_titleembed)
# # data_titleemb = pd.DataFrame(title_embedding)
# # data_frame_titleemb = data_genre.add_prefix('title_embedding_')
# # y_train_1 = pd.concat([y_train_1, data_frame_titleemb], axis=1)
# # pd.set_option('display.max_rows', None)
# # # print(y_train_1)
# # # np.shape(y_train_1)
# # Check for NaN values
# # if y_train_1.isna().any().any():
# #     print("DataFrame contains NaN values")
# # else:
# #     print("DataFrame doesn't contain NaN values")

# np.shape(y_train_1)


In [10]:
# compare train and test data and make columns for test data 
# Get the columns present in X_train_1 but not in X_test
print(np.shape(X_test))
missing_columns_X_test = list(set(X_train_1.columns) - set(X_test.columns))

# Create a DataFrame with missing columns filled with 0
missing_columns_df_X_test = [col for col in X_train_1.columns if col in missing_columns_X_test]
missing_columns_df_X_test = pd.DataFrame(0, index=X_test.index, columns=missing_columns_X_test)
# missing_columns_df_X_test = [col for col in X_train_1.columns if col in missing_columns_df_X_test]


# Concatenate missing_columns_df_X_test with X_test
X_test = pd.concat([X_test, missing_columns_df_X_test], axis=1)
X_test = X_test[X_train_1.columns]
# print(np.shape(X_train_1))
# print(np.shape(X_test))
     

(752, 8881)


In [11]:
# compare train and test data and make columns for train data 
missing_columns_X_train = list(set(X_test.columns) - set(X_train_1.columns))

#create a Dataframe with missing columns filled with 0 
missing_columns_df_X_train = [col for col in X_test.columns if col in missing_columns_X_train]
missing_columns_df_X_train = pd.DataFrame(0, index=X_train_1.index, columns=missing_columns_X_train)
# missing_columns_df_X_train = [col for col in X_test.columns if col in missing_columns_df_X_train]


#Concatenate missing_columns_df_X_train with X_train_1
X_train_1 = pd.concat([X_train_1, missing_columns_df_X_train], axis=1)
X_train_1 = X_train_1[X_test.columns]
print(np.shape(X_train_1))
print(np.shape(X_test))

(3004, 12637)
(752, 12637)


Normalise (Standardise) the data 

In [12]:
from sklearn.preprocessing import StandardScaler

# def standardise_df(df):
#     mean = df.mean(axis = 0)
#     std_vals = df.std(axis = 0)
    
#     standardised_df = (df-mean)/std_vals

#     return standardised_df


# train the model by normaling dataset with standardisation 
# X_test_stan = standardise_df(X_test)
# X_train_stan = standardise_df(X_train_1)
# y_train_stan = standardise_df(y_train_1)

# X_train, X_test, y_train, y_test_1 = train_test_split(df_train.iloc[:,:-1], df_train.iloc[:,-1], test_size=0.2, random_state=42)

# Select columns to standardize
columns_to_standardize = [col for col in X_train_1.columns if col not in categorical_cols]

# Create a StandardScaler object
scaler = StandardScaler()

# Standardize selected columns
X_train_stan = X_train_1.copy()  # Create a copy of the original DataFrame
X_train_stan[columns_to_standardize] = scaler.fit_transform(X_train_stan[columns_to_standardize])

# #delete 
# columns_to_standardize1 = [col for col in X_train.columns if col not in categorical_cols]
# X_train_stan_2 = X_train.copy()  # Create a copy of the original DataFrame
# X_train_stan_2[columns_to_standardize] = scaler.fit_transform(X_train_stan_2[columns_to_standardize])


# Select columns to standardize
columns_to_standardize = [col for col in X_test.columns if col not in categorical_cols]

# Create a StandardScaler object
scaler = StandardScaler()

# Standardize selected columns
X_test_stan = X_test.copy()  # Create a copy of the original DataFrame
X_test_stan[columns_to_standardize] = scaler.fit_transform(X_test_stan[columns_to_standardize])

#delete
# X_test_stan_2 = X_test_1.copy()  # Create a copy of the original DataFrame
# # X_test_stan_2[columns_to_standardize] = scaler.fit_transform(X_test_stan_2[columns_to_standardize])

# for column in columns_to_standardize:
#     # X_test_stan_2[column] = scaler.fit_transform(X_test_stan_2[column])
#     print(column)


# Print the standardized DataFrame
# print(X_train_stan)
X_train, X_test_1, y_train, y_test_1 = train_test_split(X_train_stan, y_train_1, test_size=0.2, random_state=42)

if X_train_stan.isna().any().any():
    print("DataFrame contains NaN values")
else:
    print("DataFrame doesn't contain NaN values")
    


DataFrame doesn't contain NaN values


Correlation Matrix 

In [17]:
# Concat X_train_1 and y_train_1 to produce full normalised training database
normalised_training_db = pd.concat([X_train_1, y_train_1], axis=1)
cor_matrix = normalised_training_db.corr()

print("Correlation Table:")
print(cor_matrix)




Gaussian Naive Bayes 

In [34]:
# train using naive bayes 

# Use Gaussian Naive_Bayes on the train dataset 
gnb = GaussianNB()
unstand_gnb = gnb.fit(X_train_1, y_train_1)

# Use Gaussina Naive Bayes to predict for the test dataset 
y_pred_gnb = unstand_gnb.predict(X_test)

stand_gnb = gnb.fit(X_train_stan, y_train_1)
y_pred_gnb_stan = stand_gnb.predict(X_test_stan)

#delete
stand_gnb_split = gnb.fit(X_train, y_train)
pred_gnb_split = stand_gnb_split.predict(X_test_1)
accuracy = accuracy_score(y_test_1, pred_gnb_split)
print("accuracy= ", accuracy)   


ids = np.arange(1, len(y_pred_gnb) + 1)
y_pred_gnb_pd = np.column_stack((ids, y_pred_gnb))
np.savetxt("y_pred_gnb.csv", y_pred_gnb_pd, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')

ids = np.arange(1, len(y_pred_gnb_stan) + 1)
y_pred_gnb_pd_stan = np.column_stack((ids, y_pred_gnb_stan))
np.savetxt("y_pred_gnb_stan.csv", y_pred_gnb_pd_stan, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')

# print("y_pred_gnb:\n", y_pred_gnb_pd)

accuracy=  0.6455906821963394


KNN Classifier 

In [35]:
from sklearn.neighbors import KNeighborsClassifier

# Create kNN classifier
k = 3
knn = KNeighborsClassifier(n_neighbors=k)

# Train the classifier 
unstand_knn = knn.fit(X_train_1, y_train_1)
stand_knn = knn.fit(X_train_stan, y_train_1)

# split 
stand_knn_split = knn.fit(X_train, y_train)
pred_knn_split = stand_knn_split.predict(X_test_1)
accuracy = accuracy_score(y_test_1, pred_knn_split)
print("accuracy= ", accuracy)

# Check for NaN values
# if X_test.isna().any().any():
#     print("DataFrame contains NaN values")
# else:
#     print("DataFrame doesn't contain NaN values")

# Predict on the test data
y_pred_knn = knn.predict(X_test)
y_pred_knn_stan = stand_knn.predict(X_test_stan)
# np.shape(X_test)

ids = np.arange(1, len(y_pred_knn) + 1)
y_pred_knn_pd = np.column_stack((ids, y_pred_knn))
np.savetxt("y_pred_knn.csv", y_pred_knn_pd, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')

ids = np.arange(1, len(y_pred_knn_stan) + 1)
y_pred_knn_stan_pd = np.column_stack((ids, y_pred_knn_stan))
np.savetxt("y_pred_stan_knn.csv", y_pred_knn_stan_pd, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')

# print("y_pred_knn:\n", y_pred_knn_pd)


accuracy=  0.6256239600665557


In [13]:
np.shape(X_train_stan)

if X_train_1.isna().any().any():
    print("DataFrame contains NaN values")
else:
    print("DataFrame doesn't contain NaN values")

if X_train_stan.isna().any().any():
    print("DataFrame contains NaN values")
else:
    print("DataFrame doesn't contain NaN values")

# Assuming your DataFrame is named df
# Check for NaN values in each column
nan_columns = X_train_stan.columns[X_train_stan.isna().any()]

# Print the columns containing NaN values
print("Columns containing NaN values:")
print(nan_columns)

DataFrame doesn't contain NaN values
DataFrame doesn't contain NaN values
Columns containing NaN values:
Index([], dtype='object')


SVM Model 

In [15]:
# SVM model 

from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

# X_train, X_test, y_train, y_test = train_test_split(df_train.iloc[:,:-1], df_train.iloc[:,-1], test_size=0.2, random_state=42)

clf = svm.SVC(kernel='linear')

# Train the SVM classifier
clf.fit(X_train_stan, y_train_1)



# Predict the labels for the test set
y_pred_SVM_stan= clf.predict(X_test_stan)

#split data 
stand_SVM_split = clf.fit(X_train, y_train)
pred_SVM_split = stand_SVM_split.predict(X_test_1)
accuracy = accuracy_score(y_test_1, pred_SVM_split)
print("accuracy= ", accuracy)

ids = np.arange(1, len(y_pred_SVM_stan) + 1)
y_pred_SVM_stan_pd = np.column_stack((ids, y_pred_SVM_stan))
np.savetxt("y_pred_stan_SVM.csv", y_pred_SVM_stan_pd, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')








accuracy=  0.6938435940099834


Neural network 

In [16]:
from sklearn.neural_network import MLPClassifier

# Define and train the neural network classifier
clf_MLP = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, alpha=0.0001,
                    solver='adam', verbose=10, random_state=42, tol=0.0001)
unstand_clf = clf_MLP.fit(X_train_1, y_train_1)
stand_clf = clf_MLP.fit(X_train_stan, y_train_1)

# Make predictions on the test set
y_pred_MLP = unstand_clf.predict(X_test)
y_pred_MLP_stan = stand_clf.predict(X_test_stan)

ids = np.arange(1, len(y_pred_MLP) + 1)
y_pred_MLP_pd = np.column_stack((ids, y_pred_MLP))
np.savetxt("y_pred_MLP.csv", y_pred_MLP_pd, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')

#split data 
stand_MLP_split = clf_MLP.fit(X_train, y_train)
pred_MLP_split = stand_MLP_split.predict(X_test_1)
accuracy = accuracy_score(y_test_1, pred_MLP_split)
print("accuracy= ", accuracy)


ids = np.arange(1, len(y_pred_MLP_stan) + 1)
y_pred_MLP_stan_pd = np.column_stack((ids, y_pred_MLP_stan))
np.savetxt("y_pred_stan_MLP.csv", y_pred_MLP_stan_pd, fmt='%d', delimiter=',', header='id,imdb_score_binned', comments='')

# print("y_pred_MLP:\n", y_pred_MLP_stan_pd)


Iteration 1, loss = 21.33074990
Iteration 2, loss = 19.18196474
Iteration 3, loss = 19.89457210
Iteration 4, loss = 20.83481888
Iteration 5, loss = 19.46401310
Iteration 6, loss = 20.20186126
Iteration 7, loss = 19.03170567
Iteration 8, loss = 18.03943925
Iteration 9, loss = 17.36843943
Iteration 10, loss = 19.39670048
Iteration 11, loss = 21.08227460
Iteration 12, loss = 20.02564866
Iteration 13, loss = 19.34344602
Iteration 14, loss = 18.12542246
Iteration 15, loss = 20.61165903
Iteration 16, loss = 18.72882189
Iteration 17, loss = 18.83811364
Iteration 18, loss = 24.15864914
Iteration 19, loss = 17.38839726
Iteration 20, loss = 16.69627769
Iteration 21, loss = 20.77169381
Iteration 22, loss = 19.19437211
Iteration 23, loss = 17.70111285
Iteration 24, loss = 17.67091304
Iteration 25, loss = 17.23835036
Iteration 26, loss = 18.10311354
Iteration 27, loss = 18.19530350
Iteration 28, loss = 17.99783768
Iteration 29, loss = 17.89825562
Iteration 30, loss = 21.26046600
Iteration 31, loss 